---
title: "GDAT 622 Investigation 2"
author: "Pavan Hothi"
date: "6/8/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

{
  c("conflicted",   
    "data.table",    
    "dplyr",         
    "drat",          
    "dtplyr",       
    "here",
    "igraph",       
    "igraphdata",    
    "intergraph",    
    "NetData",      
    "statnet"        
  ) -> package_names
  
  for (package_name in package_names) {
    if (!is.element(package_name, installed.packages()[, 1])) {
      install.packages(package_name,
                       repos = "http://cran.mtu.edu/")
    }
    library(
      package_name,
      character.only = TRUE,
      quietly = TRUE,
      verbose = FALSE
    )
  }
  rm(list = c("package_name", "package_names"))
  
  
  if (!is.element("networkdata", installed.packages()[, 1])) {
    addRepo("schochastics")
    install.packages("networkdata")
  }
  library(
    "networkdata",
    character.only = TRUE,
    quietly = TRUE,
    verbose = FALSE
  )
}

set_here()


options(show.signif.stars = FALSE)
options(digits = 4)


```


```{r}
library(R.matlab)
readMat("C:/Users/pavan/Documents/Johns Hopkins55.mat") -> johns_hops

as.data.frame(johns_hops$local.info) -> johns_hops_df
johns_hops_graph <- graph.data.frame(johns_hops_df, directed=T)

asNetwork(johns_hops_graph) -> johns_hops_net
sna::betweenness(johns_hops_net, cmode = "undirected") -> tweenness
network::set.vertex.attribute(johns_hops_net, "between", tweenness)
johns_hops_net

plot(johns_hops_net, displaylabels = TRUE, boxed.labels = FALSE,
     label.cex = 0.75, pad = 1, main = "Johns Hopkins Graph Network")

johns_hops_ergm <- ergm(johns_hops_net ~ edges)
summary(johns_hops_ergm)
anova(johns_hops_ergm)


```


```{r}

V(johns_hops_graph)$indegree <- centr_degree(johns_hops_graph, mode = "in")$res

nodes <- get.data.frame(johns_hops_graph, what="vertices")
nodes <- data.frame(id = nodes$name, title = nodes$name, group = nodes$indegree, indegree = nodes$indegree)
setnames(nodes, "indegree", "in-degree centrality")
nodes <- nodes[statnet.common::order(nodes$id, decreasing = F),]

edges <- get.data.frame(johns_hops_graph, what="edges")[1:2]

library(visNetwork)
visNetwork(nodes, edges, height = "500px", width = "100%") %>%
visOptions(selectedBy = "in-degree centrality", highlightNearest = TRUE, nodesIdSelection = TRUE)%>%
visPhysics(stabilization = FALSE)


```

